matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode7.2
language: node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

install:
  - npm install --global yarn
  - yarn global add lerna npm-check-updates
  - yarn run bootstrap
  - yarn run build
  - yarn run test

after_success:
  # - npm run --prefix conda/feedstock install-pkgs
  # - gulp --cwd conda/feedstock build
  # - gulp --cwd conda/feedstock construct
  # - ls
